### ISSUE TITLE
I got an issue with "There are no valid tests imported"

### ISSUE THREAD

**Issue by thutran01** [Xray-App/tutorial-java-cucumber#2]
That is json file to import it on xray clound please help me to correct this. Thank you so much
[
  {
    "line": 3,
    "elements": [
      {
        "start_timestamp": "2022-09-01T09:22:30.029Z",
        "line": 5,
        "name": "simple integer addition",
        "description": "",
        "id": "as-a-user--i-can-add-two-numbers;simple-integer-addition",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "duration": 2000000,
              "status": "passed"
            },
            "line": 6,
            "name": "I have entered 1 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "1",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 7,
            "name": "I have entered 2 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "2",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "And "
          },
          {
            "result": {
              "duration": 2000000,
              "status": "passed"
            },
            "line": 8,
            "name": "I press add",
            "match": {
              "location": "calculator.StepDefinitions.i_press_add()"
            },
            "keyword": "When "
          },
          {
            "result": {
              "duration": 1000000,
              "status": "passed"
            },
            "line": 9,
            "name": "the result should be 3 on the screen",
            "match": {
              "arguments": [
                {
                  "val": "3",
                  "offset": 21
                }
              ],
              "location": "calculator.StepDefinitions.the_result_should_be_on_the_screen(java.lang.Integer)"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@REQ_CALC-7931"
          }
        ]
      },
      {
        "start_timestamp": "2022-09-01T09:22:30.117Z",
        "line": 11,
        "name": "negative integer addition",
        "description": "",
        "id": "as-a-user--i-can-add-two-numbers;negative-integer-addition",
        "type": "scenario",
        "keyword": "Scenario",
        "steps": [
          {
            "result": {
              "status": "passed"
            },
            "line": 12,
            "name": "I have entered -1 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "-1",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 13,
            "name": "I have entered 2 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "2",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "And "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 14,
            "name": "I press add",
            "match": {
              "location": "calculator.StepDefinitions.i_press_add()"
            },
            "keyword": "When "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 15,
            "name": "the result should be 1 on the screen",
            "match": {
              "arguments": [
                {
                  "val": "1",
                  "offset": 21
                }
              ],
              "location": "calculator.StepDefinitions.the_result_should_be_on_the_screen(java.lang.Integer)"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@REQ_CALC-7931"
          }
        ]
      },
      {
        "start_timestamp": "2022-09-01T09:22:30.124Z",
        "line": 25,
        "name": "sum of two positive numbers",
        "description": "",
        "id": "as-a-user--i-can-add-two-numbers;sum-of-two-positive-numbers;;2",
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "status": "passed"
            },
            "line": 18,
            "name": "I have entered 20 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "20",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 19,
            "name": "I have entered 30 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "30",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "And "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 20,
            "name": "I press add",
            "match": {
              "location": "calculator.StepDefinitions.i_press_add()"
            },
            "keyword": "When "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 21,
            "name": "the result should be 50 on the screen",
            "match": {
              "arguments": [
                {
                  "val": "50",
                  "offset": 21
                }
              ],
              "location": "calculator.StepDefinitions.the_result_should_be_on_the_screen(java.lang.Integer)"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@REQ_CALC-7931"
          }
        ]
      },
      {
        "start_timestamp": "2022-09-01T09:22:30.132Z",
        "line": 26,
        "name": "sum of two positive numbers",
        "description": "",
        "id": "as-a-user--i-can-add-two-numbers;sum-of-two-positive-numbers;;3",
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "status": "passed"
            },
            "line": 18,
            "name": "I have entered 2 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "2",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 19,
            "name": "I have entered 5 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "5",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "And "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 20,
            "name": "I press add",
            "match": {
              "location": "calculator.StepDefinitions.i_press_add()"
            },
            "keyword": "When "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 21,
            "name": "the result should be 7 on the screen",
            "match": {
              "arguments": [
                {
                  "val": "7",
                  "offset": 21
                }
              ],
              "location": "calculator.StepDefinitions.the_result_should_be_on_the_screen(java.lang.Integer)"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@REQ_CALC-7931"
          }
        ]
      },
      {
        "start_timestamp": "2022-09-01T09:22:30.139Z",
        "line": 27,
        "name": "sum of two positive numbers",
        "description": "",
        "id": "as-a-user--i-can-add-two-numbers;sum-of-two-positive-numbers;;4",
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "status": "passed"
            },
            "line": 18,
            "name": "I have entered 0 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "0",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 19,
            "name": "I have entered 40 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "40",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "And "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 20,
            "name": "I press add",
            "match": {
              "location": "calculator.StepDefinitions.i_press_add()"
            },
            "keyword": "When "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 21,
            "name": "the result should be 40 on the screen",
            "match": {
              "arguments": [
                {
                  "val": "40",
                  "offset": 21
                }
              ],
              "location": "calculator.StepDefinitions.the_result_should_be_on_the_screen(java.lang.Integer)"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@REQ_CALC-7931"
          }
        ]
      },
      {
        "start_timestamp": "2022-09-01T09:22:30.149Z",
        "line": 28,
        "name": "sum of two positive numbers",
        "description": "",
        "id": "as-a-user--i-can-add-two-numbers;sum-of-two-positive-numbers;;5",
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "duration": 1000000,
              "status": "passed"
            },
            "line": 18,
            "name": "I have entered 4 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "4",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 19,
            "name": "I have entered 50 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "50",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "And "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 20,
            "name": "I press add",
            "match": {
              "location": "calculator.StepDefinitions.i_press_add()"
            },
            "keyword": "When "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 21,
            "name": "the result should be 54 on the screen",
            "match": {
              "arguments": [
                {
                  "val": "54",
                  "offset": 21
                }
              ],
              "location": "calculator.StepDefinitions.the_result_should_be_on_the_screen(java.lang.Integer)"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@REQ_CALC-7931"
          }
        ]
      },
      {
        "start_timestamp": "2022-09-01T09:22:30.158Z",
        "line": 29,
        "name": "sum of two positive numbers",
        "description": "",
        "id": "as-a-user--i-can-add-two-numbers;sum-of-two-positive-numbers;;6",
        "type": "scenario",
        "keyword": "Scenario Outline",
        "steps": [
          {
            "result": {
              "duration": 1000000,
              "status": "passed"
            },
            "line": 18,
            "name": "I have entered 5 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "5",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "Given "
          },
          {
            "result": {
              "duration": 1000000,
              "status": "passed"
            },
            "line": 19,
            "name": "I have entered 50 into the calculator",
            "match": {
              "arguments": [
                {
                  "val": "50",
                  "offset": 15
                }
              ],
              "location": "calculator.StepDefinitions.i_have_entered_into_the_calculator(java.lang.Integer)"
            },
            "keyword": "And "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 20,
            "name": "I press add",
            "match": {
              "location": "calculator.StepDefinitions.i_press_add()"
            },
            "keyword": "When "
          },
          {
            "result": {
              "status": "passed"
            },
            "line": 21,
            "name": "the result should be 55 on the screen",
            "match": {
              "arguments": [
                {
                  "val": "55",
                  "offset": 21
                }
              ],
              "location": "calculator.StepDefinitions.the_result_should_be_on_the_screen(java.lang.Integer)"
            },
            "keyword": "Then "
          }
        ],
        "tags": [
          {
            "name": "@REQ_CALC-7931"
          }
        ]
      }
    ],
    "name": "As a user, I can add two numbers",
    "description": "",
    "id": "as-a-user--i-can-add-two-numbers",
    "keyword": "Feature",
    "uri": "file:features/addition.feature",
    "tags": [
      {
        "name": "@REQ_CALC-7931",
        "type": "Tag",
        "location": {
          "line": 2,
          "column": 1
        }
      }
    ]
  }
]

**Comment by bitcoder** [comment]
The Scenarios/Scenario outlines need to be tagged with the corresponding Tests issue keys they have in Xray.. like @TEST_CALC-1234 (if the scenario is mapped to a Test issue, having issue key CALC-1234).
We cannot simply import cucumber test results; the results need to related to some existing tests, therefore we need to properly tag the scenarios beforehand  on the .feature file
