### ISSUE TITLE
Unable to link tests to existing Test Execution Key

### ISSUE THREAD

**Issue by shrubom** [Xray-App/tutorial-java-cucumber#5]
Hi @bitcoder ,

I am unable to link cucumber tests to an existing test execution issue type. I used the sample provided in this project ([tutorial-java-cucumber](https://github.com/Xray-App/tutorial-java-cucumber/tree/main)
/testexec_template.json)

**Sample Feature File:**
Feature: This is feature

  @TEST-650   ------> This is the "Test" issue type key.
  Scenario: Xray Cucumber Jenkins Test
    Given this is given statement
    When this is when statement
    Then this is then statement

Jenkins job:
![image](https://github.com/Xray-App/tutorial-java-cucumber/assets/44477101/da92d0c4-75a0-4de2-b389-485ba3b54114)

As you can see on the screenshot i have provided the test execution key that i would like to link it to. But however, it always creates a new TE. 

Any advice and help would be highly appreciated :)

Thank you.

**Comment by bitcoder** [comment]
If you use the multipart endpoint it will allow you to customize some fields on the Test Execution issue.. however it always create new test execution issues. That is a limitation of that endpoint/format. I advice you to reach out to Xray support and ask for an improvement on that endpoint.

**Comment by shrubom** [comment]
Thank you for the prompt response. Will do. :)
